name: 'Generate Envs'
description: 'Generate Envs from AssemblyInfo'

inputs:
  app:
    required: true
    description: "App Name"
  dotnet-version:
    description: 'Dotnet Version'
    default: "6.0.36"
  nuget-api-url:
    description: "NuGet URL"
  nuget-api-key:
    description: 'NuGet API key'
  nuget-api-url-2:
    description: "NuGet URL"
  nuget-api-key-2:
    description: 'NuGet API key'
  image-prefix:
    description: "full image name, ex: [image-prefix]/[image]"
  branch-production:
    description: "Production Branch"
    default: "main"
outputs:
  app:
    description: "App Name"
    value: ${{ steps.envs.outputs.app }}
  version:
    description: "App Version from AssemblyInfo"
    value: ${{ steps.envs.outputs.version }}
  image:
    description: "Image Name"
    value: ${{ steps.envs.outputs.image }}
  image-fullName:
    description: "Image Full Name"
    value: ${{ steps.envs.outputs.image-fullName }}
  tag:
    description: "Image Tag"
    value: ${{ steps.envs.outputs.tag }}
  tag-hash:
    description: "Image Tag with hash"
    value: ${{ steps.envs.outputs.tag-hash }}
  tag-latest:
    description: "Image Tag with latest"
    value: ${{ steps.envs.outputs.tag-latest }}
  build-options:
    description: "Image build options"
    value: ${{ steps.build-options.outputs.build-options }}
  branch:
    description: "Branch name"
    value: ${{ steps.envs.outputs.branch }}
  actor:
    description: "Actor"
    value: ${{ steps.envs.outputs.actor }}
  email:
    description: "Email"
    value: ${{ steps.envs.outputs.email }}

runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    - name: Add NuGet Source
      shell: bash
      if: inputs.nuget-api-url != '' && inputs.nuget-api-key != ''
      run: dotnet nuget add source --username USERNAME --password ${{ inputs.nuget-api-key }} --store-password-in-clear-text --name custom-nuget-${{ github.run_id }} "${{ inputs.nuget-api-url }}"
    - name: Add NuGet Source 2
      shell: bash
      if: inputs.nuget-api-url-2 != '' && inputs.nuget-api-key-2 != ''
      run: dotnet nuget add source --username USERNAME --password ${{ inputs.nuget-api-key-2 }} --store-password-in-clear-text --name custom-nuget-2-${{ github.run_id }} "${{ inputs.nuget-api-url-2 }}"
    - name: Install dotnet tool
      shell: bash
      run: dotnet tool install -g --prerelease netcorext.tools.assemblyinfo
    - name: Get App Version
      id: asm
      shell: bash
      run: |
        APP="${{ inputs.app }}"

        PROJECT_PATH=`find . -type f -iname "${APP}.csproj"`

        dotnet build $PROJECT_PATH -o ./dist

        echo "asm-info ./dist/${APP}.dll --simple --version"

        ASSEMBLY_VERSION=`asm-info ./dist/${APP}.dll --simple --version`

        rm -rf ./dist

        echo "version=$ASSEMBLY_VERSION" >> $GITHUB_OUTPUT
    - name: Set Environments
      id: envs
      uses: netcorext/base-info-action@dev
      with:
        app: ${{ inputs.app }}
        version: ${{ steps.asm.outputs.version }}
        image-prefix: ${{ inputs.image-prefix }}
    - name: Set Build Options
      id: build-options
      shell: bash
      run: |
        ADDITIONAL_ARGUMENTS="-c Debug --version-suffix ${{ steps.envs.outputs.tag }}"
        if [ "$GITHUB_REF_NAME" = "${{ inputs.branch-production }}" ]; then
          ADDITIONAL_ARGUMENTS="-c Release"
        fi
        echo "build-options=$ADDITIONAL_ARGUMENTS" >> $GITHUB_OUTPUT
